### ISSUE TITLE
Unclosed files from executor.py 

### ISSUE THREAD

**Issue by suliat16** [graik/biskit#41]
In the execute method of executor.py, lines 501, 503 and 524 write to file without closing it. The open file from line 524 results in a warning being raised upon successful execution of a program.

`/home/suliat16/.conda/envs/kaustenv/lib/python3.6/site-packages/biskit-3.0.0a0-py3.6.egg/biskit/exe/executor.py:524: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/rate4site_thq6mf7w.out' mode='wt' encoding='UTF-8'>
  open( self.f_out, 'wt').writelines( self.output )`

**Comment by graik** [comment]
Interesting, I always wondered why Python 2.7 was just tolerating this. Looks like 3.x is more strict. Will be addressed after merging the biskit 3 into the master branch.

**Comment by graik** [comment]
fixed in latest commit to master branch. Please check!

**Comment by suliat16** [comment]
The files written in lines 504 and 506, in the event of an error are still unclosed. However, the source of the error that I received, the open file written on line 527 looks good!

**Comment by graik** [comment]
added some more close() statements that should address this. (c30e132)
